### ISSUE TITLE
♻️Uniformise the device

### ISSUE THREAD

**Issue by Screamnox** [Convolutio/IA_languesAnciennes#9]
The one and only `device` declared as a global variable should be located in 'reconstructionModel'. (Excluding _independants_ files such as _LMs_).

Indeed, all calls leading to various files in the project (source folder) should rely on the device imposed/passed by the `ReconstructionModel`. 
And even remove this global variable to be passed as an argument during the model initialization.

_Originally posted by @Screamnox in https://github.com/Convolutio/IA_languesAnciennes/pull/6#discussion_r1389958839_

**Comment by Convolutio** [comment]
These functions and instances must have the same device defined in `ReconstructionModel`:
- [x] `compute_mutation_prob` in `Source/dynamicPrograms.py`
- [x] `EditModel` in `Source/editModel.py`
- [x] `ComputeInferenceData_*` in `data/vocab.py`
- [x] the inheritor classes of `PriorLM` in `lm/PriorLM.py`

(see [my comment in pull request #6](https://github.com/Convolutio/IA_languesAnciennes/pull/6#discussion_r1390303732))

**Comment by Screamnox** [comment]
The uniformisation was completed in the `restruct` branch at commit: 948ca084f89dcc5e264bc3ad847d44f4d0f24aab.
